---
repos:
  - repo: local
    hooks:
      - id: cargo test
        name: cargo test
        entry: cargo test
        language: system
        always_run: false
        verbose: false
        pass_filenames: false
        stages:
          - commit
          - push
        types: []
        files: ""
fail_fast: true
